kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    description: Web app running on nodejs
  labels:
    k8s-app: word-spreads-frontend
    app: word-spreads-frontend
  name: word-spreads-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: word-spreads-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: Web app running on nodejs
      labels:
        k8s-app: word-spreads-frontend
        app: word-spreads-frontend
      name: word-spreads-frontend
    spec:
      containers:
        - image: word-spreads-fe:latest
          imagePullPolicy: IfNotPresent
          name: word-spreads-frontend
          ports:
            - containerPort: 3000
      restartPolicy: Always
