apiVersion: v1
kind: Service
metadata:
  name: word-spreads-frontend-svc
  labels:
    run: word-spreads-frontend-svc
    app: word-spreads-frontend-svc
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    k8s-app: word-spreads-frontend
