name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout sources
      uses: actions/checkout@v3
    - 
      name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.2.1
      with:
        driver: docker-container
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%d-%m-%yT%H_%M')"
    - 
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.date.outputs.date }}
